---
- name: apt-get update
  apt: update_cache=true cache_valid_time=3600
  become: yes

- name: Check if slack is installed
  command: dpkg-query -W slack-desktop
  register: check_slack
  failed_when: false
  changed_when: false

- name: Download Ubuntu slack package
  get_url:
    url: "https://downloads.slack-edge.com/linux_releases/slack-desktop-{{ slack_version }}-amd64.deb"
    dest: "/tmp/slack-desktop-{{ slack_version }}-amd64.deb"
  when: check_slack.rc == 1

- name: Install Ubuntu slack package
  become: yes
  apt:
    deb: "/tmp/slack-desktop-{{ slack_version }}-amd64.deb"
  when: check_slack.rc == 1
